// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liffrudfjzcvnymhjxhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpZmZydWRmanpjdm55bWhqeGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzM2NDMsImV4cCI6MjA2MjEwOTY0M30.N9nvmmKNn4JLy_IKN1a5RiUQTMeQfUtvb0Hp2L1vFOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);